### ISSUE TITLE
Suggestion: More safeties when running without arguments.

### ISSUE THREAD

**Issue by mrcarriere** [rderik/xcibversion#2]
Just an anecdote to pass along that I'd like to share -- I don't have an immediate solution for this one so hopefully using this here as a way to discuss it.

In setting this up for our CI server, I created a symlink in /usr/local/bin to our forked git repo, and ensured that was in our path.

In testing the tool, I ran the command when I was in our home directory, and the process immediately fired off and started scouring through my home directory for files to increment. This included my local ~/Library/ folder, which definitely had a few Info.plist files. 

Thanks to the debug logging, I was able to undo the few changes before I could quit the script.

While in a CI environment this is a relatively safe thing to run, having this automatically start processing everything recursively upon invocation seems a bit dangerous. I'm debating having our fork immediately die if `--path` isn't set, but I haven't settled on that one just yet.

**Comment by rderik** [comment]
Hi @mrcarriere,

Thanks for sharing this. Yes, I agree. It is dangerous that the default behaviour is to start recursively on the current path. Your idea of making the `path` mandatory will prevent this issue and will force the user to confirm the path.

**Comment by rderik** [comment]
I created a pull request with the change, let me know if that would work for you. Or if you would like to explore other ideas I'm open for discussion.

**Comment by mrcarriere** [comment]
This would resolve my issue, thank you! Tested locally and can confirm no issues here.

**Comment by rderik** [comment]
Perfect!

I just merged the changes. and Updated the post with the changes you suggested.
